### ISSUE TITLE
invalid csrf token

### ISSUE THREAD

**Issue by 12Ritz** [Krusty84/Teamcenter_REST_API#1]
getting 403 forbidden response (invalid csrf token) when using the AWC gateway link like HTTP://hostname:port/tc/JsonRestServices/Core-2011-06-Session/login
![image](https://github.com/Krusty84/Teamcenter_REST_API/assets/133015051/cfd96eab-979e-4bd8-9dad-c398f7db64cd)

**Comment by Krusty84** [comment]
Dear @12Ritz Are you still having problem?

**Comment by Krusty84** [comment]
I have checked this collection on TC 13.3 + AWC 6, and I can not reproduce it, mmmm, in my opinion you must check your TC environment + communicate with GTAC by SDIS
